version: '3.7'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: nest_docker
    volumes:
      - ~/backup/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  api:
   image: sona93sk/nest-test
   depends_on:
    - db
   ports:
    - "4000:3000"